- app.rb
- views/styles.sass
This slightly modifies the Redis app to automatically create linked headers everywhere.
It works.  Test as needed.  :)
> Add header ids to sections for direct links

- views/buzz.sass
Screenshot of the issue : http://cl.ly/image/0I1v3O3e0827
After fix : http://cl.ly/image/253P0P0e3a1c
> Fix issue with text going out of container

- views/community.md
> Added NY Meetup Group

- downloads.json
Just a tiny grammatical error that caught my eye! :)
> Correct "coulpe" to "couple"

- views/documentation.md
Updating a sentence about acknowledging contributions for clarity.
> Updating credits text for clarity

- views/documentation.md
> Updated Documentation

- public/styles.css
Just a little fix. The void on the left really strikes the eye.
> Fix unneeded margin for the callout bar.

- TODO
StackOverflow has already been added, not sure Disqus qualifies. Not worth keeping this TODO file around for it though.
> Remove ancient TODO file

- downloads.json
> Fix typo fater to faster

- downloads.json
this was bring up from https://github.com/redis/redis/issues/7115, can you take look this？ @itamarhaber  thanks
> Update Download.json for Redis 5.0.9

- .gems
- lib/interactive/redis.rb
- lib/interactive/session.rb
Fix issues with new redis-rb.
Note that at this point I'm not sure what's the purpose of `RedisHacks` and wondering if we could just get rid of it.
> Fix (?) compatibility with redis-rb.

- app.rb
- views/clients.haml
Fixes #132 and #182. Similar to #183.
> Fixes anchors for languages named with '+' or '#'

- lib/reference.rb
> Adds nested arguments

- views/download.haml
> Adds apt and snap installation to downloads page

- makefile
> Adds a call to generate_interactive_commands.rb to deploy

- lib/interactive/commands.rb
- lib/interactive/namespace.rb
- scripts/generate_interactive_commands.rb
* Add subcommands for `CLIENT INFO` support
* Add missing custom keys for some new commands
* Exclude some new commands
> Update 6.2 commands

- app.rb
- downloads.json
- makefile
- public/styles.css
- views/download.haml
Also:
* Uses grid to display download details
* Makes deploy fail less when generating commands
> Adds cloud channel

- views/community.md
> Adds Redis Live to community page

- lib/reference.rb
Pending on and supporting https://github.com/antirez/redis-doc/pull/1223
> Adds Bitmap category

- public/styles.css
Introduced https://github.com/redis/redis-io/pull/248
> Fix CSS for mobile size which wasn't rendering

- views/documentation.md
Adding the Quick Start page to the Documentation Page. It's a useful page
> Adding the Quick Start page to the Documentation Page
